#coding=utf-8
#import libs 
import sys
import Project1_cmd
import Project1_sty
import Fun
import os
import tkinter
from   tkinter import *
import tkinter.ttk
import tkinter.font
#Add your Varial Here: (Keep This Line of comments)
#Define UI Class
class  Project1:
    def __init__(self,root,isTKroot = True):
        uiName = self.__class__.__name__
        self.uiName = uiName
        Fun.Register(uiName,'UIClass',self)
        self.root = root
        self.isTKroot = isTKroot
        Fun.Register(uiName,'root',root)
        style = Project1_sty.SetupStyle()
        if isTKroot == True:
            root.title("Form1")
            root.overrideredirect(True)
            Fun.WindowDraggable(root,0,'#ffffff')
            root.wm_attributes("-transparentcolor","#ffffff")
            Fun.CenterDlg(uiName,root,593,480)
            root['background'] = '#efefef'
        Form_1= tkinter.Canvas(root,width = 10,height = 4)
        Form_1.pack(fill=BOTH,expand=True)
        Form_1.configure(bg = "#ffffff")
        Fun.SetRootRoundRectangle(Form_1,0,0,593,480,radius=50,fill='#efefef',outline='#ffffff',width=0)
        Form_1.configure(highlightthickness = 0)
        Fun.Register(uiName,'Form_1',Form_1)
        #Create the elements of root 
        Label_2 = tkinter.Label(Form_1,text="欢迎awa")
        Fun.Register(uiName,'Label_2',Label_2,'welecome')
        Fun.SetControlPlace(uiName,'Label_2',79,17,177,48)
        Label_2.configure(relief = "flat")
        Label_2_Ft=tkinter.font.Font(family='微软雅黑', size=20,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_2.configure(font = Label_2_Ft)
        Button_3 = tkinter.Button(Form_1,text="退出")
        Fun.Register(uiName,'Button_3',Button_3,'exit')
        Fun.SetControlPlace(uiName,'Button_3',108,418,100,28)
        Button_3.configure(bg = "#ff0080")
        Button_3.configure(fg = "#000000")
        Button_3.configure(activeforeground = "#ffffff")
        Button_3.configure(relief = "groove")
        Button_3.configure(command=lambda:Project1_cmd.Button_3_onCommand(uiName,"Button_3"))
        Button_3_Ft=tkinter.font.Font(family='微软雅黑', size=9,weight='normal',slant='roman',underline=0,overstrike=0)
        Button_3.configure(font = Button_3_Ft)
        Button_9 = tkinter.Button(Form_1,text="开始部署!")
        Fun.Register(uiName,'Button_9',Button_9,'start')
        Fun.SetControlPlace(uiName,'Button_9',63,76,206,202)
        Button_9.configure(fg = "#ff0000")
        Button_9.configure(command=lambda:Project1_cmd.Button_9_onCommand(uiName,"Button_9"))
        Button_9_Ft=tkinter.font.Font(family='微软雅黑', size=20,weight='normal',slant='roman',underline=0,overstrike=0)
        Button_9.configure(font = Button_9_Ft)
        Label_12 = tkinter.Label(Form_1,text="鸣谢")
        Fun.Register(uiName,'Label_12',Label_12,'thx')
        Fun.SetControlPlace(uiName,'Label_12',355,43,47,22)
        Label_12.configure(relief = "flat")
        Label_12_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_12.configure(font = Label_12_Ft)
        Label_13 = tkinter.Label(Form_1,text="排名不分先后")
        Fun.Register(uiName,'Label_13',Label_13,'wards')
        Fun.SetControlPlace(uiName,'Label_13',339,74,100,20)
        Label_13.configure(relief = "flat")
        Label_14 = tkinter.Label(Form_1,text="honghaier-game")
        Fun.Register(uiName,'Label_14',Label_14,'honghaier-game')
        Fun.SetControlPlace(uiName,'Label_14',355,114,101,20)
        Label_14.configure(relief = "flat")
        Label_16 = tkinter.Label(Form_1,text="MrShieh-X")
        Fun.Register(uiName,'Label_16',Label_16,'MrShieh-X')
        Fun.SetControlPlace(uiName,'Label_16',355,142,62,20)
        Label_16.configure(relief = "flat")
        Button_17 = tkinter.Button(Form_1,text="Github")
        Fun.Register(uiName,'Button_17',Button_17,'MrShieh-X_github')
        Fun.SetControlPlace(uiName,'Button_17',417,145,50,17)
        Button_17.configure(fg = "#0000ff")
        Button_17.configure(relief = "flat")
        Button_17.configure(command=lambda:Project1_cmd.Button_17_onCommand(uiName,"Button_17"))
        Label_18 = tkinter.Label(Form_1,text="OneplusMEMZ(达成成就:自己感谢自己)")
        Fun.Register(uiName,'Label_18',Label_18,'OneplusMEMZ')
        Fun.SetControlPlace(uiName,'Label_18',355,170,219,16)
        Label_18.configure(relief = "flat")
        Button_19 = tkinter.Button(Form_1,text="Github")
        Fun.Register(uiName,'Button_19',Button_19,'OneplusMEMZ_github')
        Fun.SetControlPlace(uiName,'Button_19',355,193,42,17)
        Button_19.configure(fg = "#0000ff")
        Button_19.configure(relief = "flat")
        Button_19.configure(command=lambda:Project1_cmd.Button_19_onCommand(uiName,"Button_19"))
        Button_20 = tkinter.Button(Form_1,text="Gitee")
        Fun.Register(uiName,'Button_20',Button_20)
        Fun.SetControlPlace(uiName,'Button_20',474,145,45,17)
        Button_20.configure(fg = "#0000ff")
        Button_20.configure(relief = "flat")
        Button_20.configure(command=lambda:Project1_cmd.Button_20_onCommand(uiName,"Button_20"))
        Label_21 = tkinter.Label(Form_1,text="感谢Ta们的辛勤付出与努力,")
        Fun.Register(uiName,'Label_21',Label_21,'text_1')
        Fun.SetControlPlace(uiName,'Label_21',371,258,155,20)
        Label_21.configure(relief = "flat")
        Label_22 = tkinter.Label(Form_1,text="没有他们这个项目就无法实现!")
        Fun.Register(uiName,'Label_22',Label_22,'text_2')
        Fun.SetControlPlace(uiName,'Label_22',371,278,163,11)
        Label_22.configure(relief = "flat")
        Label_23 = tkinter.Label(Form_1,text="另外也感谢广大的沙雕网友们!")
        Fun.Register(uiName,'Label_23',Label_23,'text_3')
        Fun.SetControlPlace(uiName,'Label_23',374,292,160,13)
        Label_23.configure(relief = "flat")
        Label_24 = tkinter.Label(Form_1,text="是你们给了我前进的动力!")
        Fun.Register(uiName,'Label_24',Label_24,'text_4')
        Fun.SetControlPlace(uiName,'Label_24',371,308,137,11)
        Label_24.configure(relief = "flat")
        Label_25 = tkinter.Label(Form_1,text="加入QQ蕉♂流♂群")
        Fun.Register(uiName,'Label_25',Label_25,'join_qun_text')
        Fun.SetControlPlace(uiName,'Label_25',317,331,176,20)
        Label_25.configure(bg = "#8cc6ff")
        Label_25.configure(fg = "#0080ff")
        Label_25.configure(relief = "flat")
        Label_25_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_25.configure(font = Label_25_Ft)
        Button_26 = tkinter.Button(Form_1,text="冲！")
        Fun.Register(uiName,'Button_26',Button_26,'join_qun_button')
        Fun.SetControlPlace(uiName,'Button_26',355,359,197,87)
        Button_26.configure(bg = "#0080ff")
        Button_26.configure(fg = "#c0c0c0")
        Button_26.configure(activebackground = "#0080ff")
        Button_26.configure(relief = "flat")
        Button_26.configure(command=lambda:Project1_cmd.Button_26_onCommand(uiName,"Button_26"))
        Button_26_Ft=tkinter.font.Font(family='微软雅黑', size=20,weight='normal',slant='roman',underline=0,overstrike=0)
        Button_26.configure(font = Button_26_Ft)
        Button_27 = tkinter.Button(Form_1,text="Github")
        Fun.Register(uiName,'Button_27',Button_27,'hhe-g_github')
        Fun.SetControlPlace(uiName,'Button_27',456,114,47,21)
        Button_27.configure(fg = "#0000ff")
        Button_27.configure(relief = "flat")
        Button_27.configure(command=lambda:Project1_cmd.Button_27_onCommand(uiName,"Button_27"))
        Label_28 = tkinter.Label(Form_1,text="本软件仅供交流学习使用，下载后请在24小时内删除")
        Fun.Register(uiName,'Label_28',Label_28)
        Fun.SetControlPlace(uiName,'Label_28',21,299,282,20)
        Label_28.configure(relief = "flat")
        Label_29 = tkinter.Label(Form_1,text="使用本软件造成的一切后果，本人不负责任。")
        Fun.Register(uiName,'Label_29',Label_29)
        Fun.SetControlPlace(uiName,'Label_29',39,323,247,24)
        Label_29.configure(relief = "flat")
        Label_30 = tkinter.Label(Form_1,text="部分文件来自网络，侵权删")
        Fun.Register(uiName,'Label_30',Label_30)
        Fun.SetControlPlace(uiName,'Label_30',68,347,175,23)
        Label_30.configure(relief = "flat")
        Label_31 = tkinter.Label(Form_1,text="如未安装Java,请自行搜索安装")
        Fun.Register(uiName,'Label_31',Label_31)
        Fun.SetControlPlace(uiName,'Label_31',68,370,180,20)
        Label_31.configure(fg = "#ff0000")
        Label_31.configure(relief = "flat")
        Label_32 = tkinter.Label(Form_1,text="如不能正常启动，请自行修改cmcl.json!")
        Fun.Register(uiName,'Label_32',Label_32)
        Fun.SetControlPlace(uiName,'Label_32',21,391,282,20)
        Label_32.configure(fg = "#ff0000")
        Label_32.configure(relief = "flat")
        #Inital all element's Data 
        Fun.InitElementData(uiName)
        #Call Form_1's OnLoad Function
        Project1_cmd.Form_1_onLoad(uiName)
        #Add Some Logic Code Here: (Keep This Line of comments)


        #Exit Application: (Keep This Line of comments)
        if self.isTKroot == True:
            self.root.protocol('WM_DELETE_WINDOW', self.exit)

    def exit(self):
        if self.isTKroot == True:
            self.root.destroy()

#Create the root of Kinter 
if  __name__ == '__main__':
    root = tkinter.Tk()
    MyDlg = Project1(root)
    root.mainloop()
